<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'CSweet.Office.Contracts'">
    <ProjectReference Condition="'$(UseLocalOfficeContracts)' == 'true'"
                      Include="$(CSweetOfficeContractsRepositoryRoot)\src\CSweet.Office.Contracts\CSweet.Office.Contracts.csproj" />
    <PackageReference Condition="'$(UseLocalOfficeContracts)' != 'true'"
                      Include="CSweet.Office.Contracts" />
    <Compile Include="$(MSBuildThisFileDirectory)Office.GlobalUsings.cs" Link="Office.GlobalUsings.cs" />
  </ItemGroup>
</Project>
