<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Abstractions\CSweet.SatelliteOffice.Runtime.Abstractions.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.AppleVirtualization\CSweet.SatelliteOffice.Runtime.AppleVirtualization.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Firecracker\CSweet.SatelliteOffice.Runtime.Firecracker.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.HyperV\CSweet.SatelliteOffice.Runtime.HyperV.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.LocalRpc\CSweet.SatelliteOffice.Runtime.LocalRpc.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Protocol\CSweet.SatelliteOffice.Runtime.Protocol.csproj" />
  </ItemGroup>
</Project>
