<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Abstractions\CSweet.SatelliteOffice.Runtime.Abstractions.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Artifacts\CSweet.SatelliteOffice.Runtime.Artifacts.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.LocalRpc\CSweet.SatelliteOffice.Runtime.LocalRpc.csproj" />
    <ProjectReference Include="..\CSweet.SatelliteOffice.Runtime.Protocol\CSweet.SatelliteOffice.Runtime.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CSweet.SatelliteOffice.Tests" />
  </ItemGroup>
</Project>
